spring:
  application:
    name: com.knox.notification
  mail:
    host: ${HOST:smtp.gmail.com}
    port: ${PORT:587}
    username: ${MAIL:shamsulansari309@gmail.com}
    password: ${MAIL_PASSWORD:SMTP-PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs.enabled: true

email-templates:
  templates:
    WELCOME:
      template-id: welcome
      subject-line: Hello World

whats-app:
  url: ${WHATSAPP_URL:https://graph.facebook.com/v22.0/{APP-ID}/messages}
  token: ${WHATSAPP_ACCESS_TOKEN:PASTE_YOUR_TOKEN}
  template:
    WELCOME: "hello_world1"